id: P004191
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:59:43.602621
source_metadata:
  id: bdr:W1KG4304
  title: ཆོས་འབྱུང་བསྟན་པའི་པདྨ་རྒྱས་པའི་ཉིན་བྱེད
  author: ''
  volumes:
    189f8b49fa3a4aa28936206dd4d85b96:
      image_group_id: I1PD100515
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
