id: I38A9CC9E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:23:14+00:00'
last_modified: '2022-06-07T20:56:42.541473+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4304
  title: ཆོས་འབྱུང་བསྟན་པའི་པདྨ་རྒྱས་པའི་ཉིན་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B74A:
      image_group_id: I1PD100515
      title: ''
      total_pages: 530
      order: 1
      base_file: B74A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
